import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/main/components/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-full">
        <Header />
        <main className="px-28">{children}</main>
      </body>
    </html>
  );
}
